---
- name: directory file creation play
  hosts: webservers
  tasks: 
    - name: first task directory creation
      ansible.builtin.file:
        path: "{{DIRECTORY}}"
        state: directory
    - name: file creation
      ansible.builtin.file:
        path: "{{DIRECTORY}}/{{FILE}}"
        state: touch
    - name: file content addition
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"
